# Generated by Django 5.1 on 2024-08-26 11:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_room_options_rename_update_room_updated'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='patricipants',
            field=models.ManyToManyField(blank=True, related_name='patricipants', to=settings.AUTH_USER_MODEL),
        ),
    ]
